<a href="https://colab.research.google.com/github/Maheshwar-Pant/ML_lab/blob/main/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab 4 : Logistic Regression ,Support Vector Classification(SVC) , and Support Vector Regression (SVR)

This lab session focuses on implementing Logistic Regression , Support Vector Classification (SVC) , and Support Vector Regression (SVR) using Pyhton ans Scikit-learn

##Part A: Logistic Regression

### Dataset :
Use the Breast Cancer dataset available in Scikit-learn

### Task 1 :Load the Dataset

In [17]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
x = data.data
y = data.target

## Task 2 : Explore the Dataset

###1. Display the shape of x and y.

In [11]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

# Convert features to DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)
# Add target column
df['target'] = data.target
print(df.shape)

(569, 31)

### 2.Print the first five rows.

In [10]:
print(df.head())

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

###3. Identify :Number of samples

In [12]:
print("Samples:", df.shape[0])

Samples: 569

### Number of features

In [14]:
print("Features:",df.shape[1]-1 )

Features: 30

### Number of classes

In [15]:
print("Classes:",df['target'].nunique())

Classes: 2

## Task 3 : Split the Dataset

### Split the data into : 80% training and 20% testing

In [22]:
from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

## Task 4: Standardize Features

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
##Train  the logistic regression model using default parameters.

from sklearn.linear_model import LogisticRegression

# Initialize model (default parameters)
model = LogisticRegression()

# Train (fit)
model.fit(X_train, y_train)

LogisticRegression()

In [31]:
## Task 6: Make Predictions
## Predict class labels for the test set.
y_pred = model.predict(X_test)

print(y_pred[:10])

[1 0 0 1 1 0 0 0 1 1]

In [32]:
##Compute following parameters to evaluate your model:
##1. Accuracy
#2. Precision
#3. Recall
#4. F1-score
#5. Confusion Matrix

In [33]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9736842105263158
Precision: 0.9722222222222222
Recall: 0.9859154929577465
F1 Score: 0.9790209790209791
Confusion Matrix:
 [[41  2]
 [ 1 70]]

##Task 8: Interpret Coefficients
Display the coefficients of the trained model.

In [34]:
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

# Sort for interpretation
coef_df = coef_df.sort_values(by='Coefficient', ascending=False)

print(coef_df)

                    Feature  Coefficient
15        compactness error     0.682491
19  fractal dimension error     0.616230
5          mean compactness     0.540164
18           symmetry error     0.500425
8             mean symmetry     0.236119
11            texture error     0.188877
16          concavity error     0.175275
9    mean fractal dimension     0.075921
25        worst compactness     0.016110
4           mean smoothness    -0.071667
29  worst fractal dimension    -0.157414
17     concave points error    -0.311300
14         smoothness error    -0.313307
1              mean texture    -0.387326
2            mean perimeter    -0.393432
0               mean radius    -0.431904
3                 mean area    -0.465210
24         worst smoothness    -0.544170
22          worst perimeter    -0.589453
12          perimeter error    -0.610583
27     worst concave points    -0.778217
6            mean concavity    -0.801458
23               worst area    -0.841846
20             worst radius    -0.879840
13               area error    -0.907186
26          worst concavity    -0.943053
7       mean concave points    -1.119804
28           worst symmetry    -1.208200
10             radius error    -1.268178
21            worst texture    -1.350606

###Questions:
1. Which feature has the largest positive coefficient?

In [35]:
coef_df.iloc[0]

Feature        compactness error
Coefficient             0.682491
Name: 15, dtype: object

###2. which feature has the largest negative coefficient ?

In [36]:
coef_df.iloc[-1]

Feature        worst texture
Coefficient        -1.350606
Name: 21, dtype: object

3. What does the sign of a coefficient indicate ?

Positive coefficient (+)
→ As feature value increases → probability of class 1 increases
Negative coefficient (−)
→ As feature value increases → probability of class 1 decreases

####Part B: Support Vector Classification(SVC)

### Dataset Use the Iris Dataset

###Task1: Load the Dataset

In [38]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

# Convert to DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

print(df.head())

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

###Task 2 : Exploratory Analysis: Determine
###1.Number of classes
###2.Number of features
###3.Class labels

In [39]:
import numpy as np

# Number of classes
print("Number of classes:", len(np.unique(df['target'])))

# Number of features
print("Number of features:", df.shape[1] - 1)

# Class labels
print("Class labels:", iris.target_names)

Number of classes: 3
Number of features: 4
Class labels: ['setosa' 'versicolor' 'virginica']

In [40]:
from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [41]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = pd.DataFrame(scaler.fit_transform(X_train), columns=X.columns)
X_test = pd.DataFrame(scaler.transform(X_test), columns=X.columns)

In [42]:
from sklearn.svm import SVC

svc_linear = SVC(kernel='linear')
svc_linear.fit(X_train, y_train)

SVC(kernel='linear')

In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred_linear = svc_linear.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_linear))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_linear))
print("Classification Report:\n", classification_report(y_test, y_pred_linear))

Accuracy: 0.9777777777777777
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

In [44]:
svc_rbf = SVC(kernel='rbf')
svc_rbf.fit(X_train, y_train)

y_pred_rbf = svc_rbf.predict(X_test)

print("RBF Accuracy:", accuracy_score(y_test, y_pred_rbf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rbf))
print("Classification Report:\n", classification_report(y_test, y_pred_rbf))

RBF Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [45]:
import pandas as pd

accuracy_linear = accuracy_score(y_test, y_pred_linear)
accuracy_rbf = accuracy_score(y_test, y_pred_rbf)

comparison = pd.DataFrame({
    'Kernel': ['Linear', 'RBF'],
    'Accuracy': [accuracy_linear, accuracy_rbf]
})

print(comparison)

   Kernel  Accuracy
0  Linear  0.977778
1     RBF  1.000000